bracketSpacing: true
plugins:
  - "prettier-plugin-solidity"
printWidth: 120
proseWrap: "always"
singleQuote: false
tabWidth: 2
trailingComma: "all"

overrides:
  - files: "*.sol"
    options:
      compiler: "0.8.24"
      parser: "solidity-parse"
      tabWidth: 4
  - files: "*.ts"
    options:
      parser: "typescript"
